POST http://localhost:3001/api/blogs/
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik9sbGkiLCJpZCI6IjVhODFiZmY2OTM5ZTYwMTQ1ZGRjN2YyNCIsImlhdCI6MTUxODQ2MjYwOH0.Q6PayWZKdAOvDLIbsCf72csM2Db1j_GKXxA5dTsFqTY

{
    "title": "Blogi",
    "author": "Olli",
    "url": "www.blog.fi",
    "likes": 0,
    "userId": "5a81bff6939e60145ddc7f24"
}