POST http://localhost:3001/api/blogs/
content-type: application/json

{
    "title": "Blogi",
    "author": "Olli",
    "url": "www.blog.fi",
    "likes": 0,
    "userId": "5a81bff6939e60145ddc7f24"
}